Feature/update project description
bbortt/event-planner pull request #102
Opened 2020-12-05 16:09 UTC by zeroplexer

Evtl soll in einem weiteren Schritt der Button nur für den Projektadministrator angezeigt werden

2020-12-10 14:22 UTC, bbortt requested changes

2020-12-10 14:22 UTC, bbortt commented on src/main/webapp/app/view/project/admin/project-admin-update.component.ts
> +    selectedUser: [null, []],
administrator (`selectedUser`) kann nicht bearbeitet werden. `startTime` und `endTime` bin ich auch eher dagegen.

2020-12-10 14:22 UTC, bbortt commented on src/main/webapp/app/view/project/admin/project-admin-update.component.ts
> +  endMoment = moment();
diese values müssten auf den aktuellen Wert des Projektes gesetzt werden, nicht? ist ja das Update hier..

2020-12-10 14:22 UTC, bbortt commented on src/main/webapp/app/view/project/admin/project-admin.component.ts
> +    this.projectService.find(this.project!.id!).subscribe(project => (this.project = project.body as Project));
das return vom service ist eine `HttpResponse`, deshalb: `subscribe(response =>`

2020-12-10 14:22 UTC, bbortt commented on src/main/webapp/app/view/project/admin/project-admin.module.ts
> +  imports: [EventPlannerSharedModule, NgxAutocompleteModule, RouterModule.forChild(PROJECT_ADMIN_ROUTES), MatDatetimepickerModule],
wollen wir Start-/End-Zeit wirklich bearbeiten? das müsste dann eine Nach-Validierung aller Events zur Folge haben.. habe ich auch im `project-admin-update.component.ts` kommentiert.
sonst sicherlich die Routen als letzten Import.

2020-12-10 14:22 UTC, bbortt commented on src/main/webapp/app/view/project/admin/project-admin.component.ts
> +import { ProjectService } from 'app/entities/project/project.service';
```ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

import { Subscription } from 'rxjs';

import { JhiEventManager } from 'ng-jhipster';

import { Project } from 'app/shared/model/project.model';
import { ProjectService } from 'app/entities/project/project.service';
```

2020-12-10 14:22 UTC, bbortt commented on src/main/webapp/app/view/modal-outlet.routes.ts
> +    outlet: 'modal',
der Zugriff auf die Routen müsste auch eingeschränkt werden (mittels `canActivate`). ebenso die unteren, für Responsibilities und Invitations :)

2020-12-10 14:22 UTC, bbortt commented on src/main/webapp/app/view/modal-outlet.routes.ts
> +import { ProjectAdminUpdateModalComponent } from 'app/view/project/admin/project-admin-update-modal.component';
bitte die Auflistung gemäss der Verwendung unten in Reihenfolge bringen.. und ohne Leerzeilen :)

2020-12-11 07:36 UTC, zeroplexer commented on src/main/webapp/app/view/project/admin/project-admin-update.component.ts
> +    selectedUser: [null, []],
Was ist, wenn das Turnfest um eine Woche verschoben wird ? Dann sollte man `startTime` und `endTime` anpassen können

2020-12-11 07:46 UTC, zeroplexer commented on src/main/webapp/app/view/project/admin/project-admin-update.component.ts
> +  endMoment = moment();
Diese Felder werden gebraucht, damit `endTime` nach der Eingabe von `startTime` automatisch auf die gleiche Zeit gestellt wird.

2020-12-11 07:53 UTC, zeroplexer commented on src/main/webapp/app/view/project/admin/project-admin-update.component.ts
> +    selectedUser: [null, []],
Frage mich wie häufig dieses Szenario auftreten kann. Die Daten werden wohl schon ein Jahr im voraus festgelegt. Mit der ganzen Planung im voraus ist es wohl gar nicht mehr möglich das Turnfest zu verschieben oder?

2020-12-11 08:05 UTC, zeroplexer commented on src/main/webapp/app/view/modal-outlet.routes.ts
> +    outlet: 'modal',
Habe versucht auf die Seite `/project/7/admin/locations(modal:projects/7/edit)` zuzugreifen als Viewer. Hat nicht geklappt (accessdenied).
Denke es wird schon von `PROJECT_ADMIN_ROUTES` abgedeckt.

2020-12-11 10:33 UTC, bbortt commented on src/main/webapp/app/view/modal-outlet.routes.ts
> +    outlet: 'modal',
ja, hier wird allerdings der `project/:projectId/admin` Zugriff verhindert - nicht die Modal-Route. versuch mal einfach `/(modal:projects/7/edit)` zuzugreiffen?

2020-12-11 10:35 UTC, bbortt commented on src/main/webapp/app/view/project/admin/project-admin-update.component.ts
> +    selectedUser: [null, []],
achso.. so wie wir - wir haben unser Turnfest vom 2021 inst 2022 verschoben. allerdings denke ich, muss man dann einen neuen Zeitplan / neues Drehbuch erstellen.

2020-12-11 10:36 UTC, bbortt commented on src/main/webapp/app/view/project/admin/project-admin-update.component.ts
> +  endMoment = moment();
ja, aber initial steht es jetzt auf dem heutigen Datum, nicht? oder zeigt es korrekt das Start-/ End-Datum des selektierten Projektes an?

2020-12-12 09:38 UTC, zeroplexer commented on src/main/webapp/app/view/project/admin/project-admin-update.component.ts
> +    selectedUser: [null, []],
Ja das stimmt. Dann werde ich das bearbeiten der Zeit entfernen

2020-12-12 09:40 UTC, zeroplexer commented on src/main/webapp/app/view/project/admin/project-admin.module.ts
> +  imports: [EventPlannerSharedModule, NgxAutocompleteModule, RouterModule.forChild(PROJECT_ADMIN_ROUTES), MatDatetimepickerModule],
Nein, die Zeiten sollten nicht bearbeitet werden. Werde es entfernen

2020-12-12 09:48 UTC, zeroplexer commented on src/main/webapp/app/view/modal-outlet.routes.ts
> +    outlet: 'modal',
Stimmt du hast recht :)

2020-12-13 09:17 UTC, bbortt approved these changes
/lgtm 🚀

2020-12-15 11:24 UTC, merged