#12 basic screenplay grouped by sections.
bbortt/event-planner pull request #135
Opened 2020-12-30 19:06 UTC by bbortt

using the `devextreme` "Scheduler" component. it is limited to day-to-day view at the moment. no CRUD options yet, just readonly events.

![image](https://user-images.githubusercontent.com/12272901/103375359-5a1b5a00-4ada-11eb-8434-464c6797de64.png)

2020-12-31 09:02 UTC, zeroplexer requested changes
Wenn ich auf die Locationseite http://localhost:9000/project/4/admin/locations gehe, erhalte ich pro Location einen `Interner Serverfehler.`
![image](https://user-images.githubusercontent.com/41778593/103403042-24648880-4b4f-11eb-845e-f3434f58a113.png)

2020-12-31 12:28 UTC, bbortt commented on src/main/java/io/github/bbortt/event/planner/repository/xy.sql
> +select *
achso xD das sollte da nicht sein^^ da habe ich nur das Hibernate Query überprüft!

2020-12-31 12:29 UTC, bbortt commented on src/main/webapp/app/view/project/screenplay/project-screenplay-location.component.ts
> +        console.log('data - events  : ', this.events);
da ging ein Commit vergessen. pushe ich noch 👍🏼

2020-12-31 12:30 UTC, bbortt commented on src/main/webapp/app/entities/section/section.service.ts
> +  protected convertDateFromServer(res: EntityResponseType): EntityResponseType {
nein, siehe Kommentar unten..

2020-12-31 12:30 UTC, bbortt commented
simmt.. [das Problem](https://github.com/bbortt/event-planner/pull/135#pullrequestreview-560295357) wollte ich mir noch anschauen. die Tests schlagen deshalb auch noch fehl!

2021-01-01 10:21 UTC, zeroplexer approved these changes
Sieht schon sehr gut aus 👍 
Im einem nächsten Schritt sollte der Scheduler noch Übersetzt werden. Wenn möglich die Uhrzeit auf 24h umstellen. Denke der Button `All day`  wird in unserem Fall nicht benötigt. `Repeat` könnte wohl hilfreich sein um z.B Mittagspause einzutragen. `sectionId` sollte `section` lauten

2021-01-01 13:17 UTC, merged