Feature/#12 screenplay crud functionality
bbortt/event-planner pull request #141
Opened 2021-01-03 12:27 UTC by bbortt

PR contains:
* create and update functionality for `Event`s
* secure `Event` REST API

2021-01-03 17:07 UTC, zeroplexer requested changes
Wenn ich ein Event bearbeite erhalte ich einen `Interner Serverfehler`

```bash
2021-01-03 18:46:31.262 DEBUG 11828 --- [  XNIO-1 task-1] i.g.b.e.planner.web.rest.EventResource   : Enter: updateEvent() with argument[s] = [Event{id=2, name='Happy Hour', description='null', startTime='2020-12-10T11:00Z[UTC]', endTime='2020-12-10T12:30Z[UTC]'}]
2021-01-03 18:46:31.262 DEBUG 11828 --- [  XNIO-1 task-1] i.g.b.e.planner.web.rest.EventResource   : REST request to update Event : Event{id=2, name='Happy Hour', description='null', startTime='2020-12-10T11:00Z[UTC]', endTime='2020-12-10T12:30Z[UTC]'}
2021-01-03 18:46:31.263 DEBUG 11828 --- [  XNIO-1 task-1] i.g.b.e.planner.service.EventService     : Enter: save() with argument[s] = [Event{id=2, name='Happy Hour', description='null', startTime='2020-12-10T11:00Z[UTC]', endTime='2020-12-10T12:30Z[UTC]'}]
2021-01-03 18:46:31.263 DEBUG 11828 --- [  XNIO-1 task-1] i.g.b.e.planner.service.EventService     : Request to save Event : Event{id=2, name='Happy Hour', description='null', startTime='2020-12-10T11:00Z[UTC]', endTime='2020-12-10T12:30Z[UTC]'}
Hibernate: select event0_.id as id1_0_0_, event0_.description as descript2_0_0_, event0_.end_time as end_time3_0_0_, event0_.name as name4_0_0_, event0_.responsibility_id as responsi6_0_0_, event0_.start_time as start_ti5_0_0_, event0_.jhi_user_id as jhi_user7_0_0_ from event event0_ where event0_.id=?
Hibernate: select sections0_.event_id as event_id2_13_8_, sections0_.section_id as section_1_13_8_, section1_.id as id1_12_0_, section1_.location_id as location3_12_0_, section1_.name as name2_12_0_, section1_.responsibility_id as responsi4_12_0_, section1_.jhi_user_id as jhi_user5_12_0_, location2_.id as id1_7_1_, location2_.name as name2_7_1_, location2_.project_id as project_3_7_1_, location2_.responsibility_id as responsi4_7_1_, location2_.jhi_user_id as jhi_user5_7_1_, project3_.id as id1_9_2_, project3_.description as descript2_9_2_, project3_.end_time as end_time3_9_2_, project3_.name as name4_9_2_, project3_.start_time as start_ti5_9_2_, responsibi4_.id as id1_10_3_, responsibi4_.name as name2_10_3_, responsibi4_.project_id as project_3_10_3_, project5_.id as id1_9_4_, project5_.description as descript2_9_4_, project5_.end_time as end_time3_9_4_, project5_.name as name4_9_4_, project5_.start_time as start_ti5_9_4_, user6_.id as id1_5_5_, user6_.created_by as created_2_5_5_, user6_.created_date as created_3_5_5_, user6_.last_modified_by as last_mod4_5_5_, user6_.last_modified_date as last_mod5_5_5_, user6_.activated as activate6_5_5_, user6_.activation_key as activati7_5_5_, user6_.email as email8_5_5_, user6_.first_name as first_na9_5_5_, user6_.image_url as image_u10_5_5_, user6_.lang_key as lang_ke11_5_5_, user6_.last_name as last_na12_5_5_, user6_.login as login13_5_5_, user6_.password_hash as passwor14_5_5_, user6_.reset_date as reset_d15_5_5_, user6_.reset_key as reset_k16_5_5_, responsibi7_.id as id1_10_6_, responsibi7_.name as name2_10_6_, responsibi7_.project_id as project_3_10_6_, user8_.id as id1_5_7_, user8_.created_by as created_2_5_7_, user8_.created_date as created_3_5_7_, user8_.last_modified_by as last_mod4_5_7_, user8_.last_modified_date as last_mod5_5_7_, user8_.activated as activate6_5_7_, user8_.activation_key as activati7_5_7_, user8_.email as email8_5_7_, user8_.first_name as first_na9_5_7_, user8_.image_url as image_u10_5_7_, user8_.lang_key as lang_ke11_5_7_, user8_.last_name as last_na12_5_7_, user8_.login as login13_5_7_, user8_.password_hash as passwor14_5_7_, user8_.reset_date as reset_d15_5_7_, user8_.reset_key as reset_k16_5_7_ from section_has_events sections0_ inner join section section1_ on sections0_.section_id=section1_.id inner join location location2_ on section1_.location_id=location2_.id left outer join project project3_ on location2_.project_id=project3_.id left outer join responsibility responsibi4_ on location2_.responsibility_id=responsibi4_.id left outer join project project5_ on responsibi4_.project_id=project5_.id left outer join jhi_user user6_ on location2_.jhi_user_id=user6_.id inner join responsibility responsibi7_ on section1_.responsibility_id=responsibi7_.id left outer join jhi_user user8_ on section1_.jhi_user_id=user8_.id where sections0_.event_id=?
Hibernate: select section0_.id as id1_12_0_, section0_.location_id as location3_12_0_, section0_.name as name2_12_0_, section0_.responsibility_id as responsi4_12_0_, section0_.jhi_user_id as jhi_user5_12_0_, location1_.id as id1_7_1_, location1_.name as name2_7_1_, location1_.project_id as project_3_7_1_, location1_.responsibility_id as responsi4_7_1_, location1_.jhi_user_id as jhi_user5_7_1_, project2_.id as id1_9_2_, project2_.description as descript2_9_2_, project2_.end_time as end_time3_9_2_, project2_.name as name4_9_2_, project2_.start_time as start_ti5_9_2_, responsibi3_.id as id1_10_3_, responsibi3_.name as name2_10_3_, responsibi3_.project_id as project_3_10_3_, project4_.id as id1_9_4_, project4_.description as descript2_9_4_, project4_.end_time as end_time3_9_4_, project4_.name as name4_9_4_, project4_.start_time as start_ti5_9_4_, user5_.id as id1_5_5_, user5_.created_by as created_2_5_5_, user5_.created_date as created_3_5_5_, user5_.last_modified_by as last_mod4_5_5_, user5_.last_modified_date as last_mod5_5_5_, user5_.activated as activate6_5_5_, user5_.activation_key as activati7_5_5_, user5_.email as email8_5_5_, user5_.first_name as first_na9_5_5_, user5_.image_url as image_u10_5_5_, user5_.lang_key as lang_ke11_5_5_, user5_.last_name as last_na12_5_5_, user5_.login as login13_5_5_, user5_.password_hash as passwor14_5_5_, user5_.reset_date as reset_d15_5_5_, user5_.reset_key as reset_k16_5_5_, responsibi6_.id as id1_10_6_, responsibi6_.name as name2_10_6_, responsibi6_.project_id as project_3_10_6_, user7_.id as id1_5_7_, user7_.created_by as created_2_5_7_, user7_.created_date as created_3_5_7_, user7_.last_modified_by as last_mod4_5_7_, user7_.last_modified_date as last_mod5_5_7_, user7_.activated as activate6_5_7_, user7_.activation_key as activati7_5_7_, user7_.email as email8_5_7_, user7_.first_name as first_na9_5_7_, user7_.image_url as image_u10_5_7_, user7_.lang_key as lang_ke11_5_7_, user7_.last_name as last_na12_5_7_, user7_.login as login13_5_7_, user7_.password_hash as passwor14_5_7_, user7_.reset_date as reset_d15_5_7_, user7_.reset_key as reset_k16_5_7_ from section section0_ inner join location location1_ on section0_.location_id=location1_.id inner join project project2_ on location1_.project_id=project2_.id left outer join responsibility responsibi3_ on location1_.responsibility_id=responsibi3_.id left outer join project project4_ on responsibi3_.project_id=project4_.id left outer join jhi_user user5_ on location1_.jhi_user_id=user5_.id inner join responsibility responsibi6_ on section0_.responsibility_id=responsibi6_.id left outer join jhi_user user7_ on section0_.jhi_user_id=user7_.id where section0_.id=?
2021-01-03 18:46:31.286 ERROR 11828 --- [  XNIO-1 task-1] i.g.b.e.planner.service.EventService     : Exception in save() with cause = 'javax.persistence.EntityNotFoundException: Unable to find io.github.bbortt.event.planner.domain.Section with id 2' and exception = 'Unable to find io.github.bbortt.event.planner.domain.Section with id 2; nested exception is javax.persistence.EntityNotFoundException: Unable to find io.github.bbortt.event.planner.domain.Section with id 2'

org.springframework.orm.jpa.JpaObjectRetrievalFailureException: Unable to find io.github.bbortt.event.planner.domain.Section with id 2; nested exception is javax.persistence.EntityNotFoundException: Unable to find io.github.bbortt.event.planner.domain.Section with id 2
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:379)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:257)
	at org.springframework.orm.jpa.AbstractEntityMana [...]

2021-01-03 17:22 UTC, bbortt commented on src/main/webapp/app/shared/model/scheduler/event.scheduler.ts
> +  originalEvent?: Event;
hm, der `SchedulerEvent` ist wie ein data-transfer-object für den `Scheduler` von `devextreme`. damit klar ist aus welcher Entität er entspringt (also, welche vom Backend geladen wurde) nenne ich diesen `originalEvent: Event`. sobald etwas am Scheduler bearbeitet wird muss anhand dieses wiederum der originale `Event` abgeleitet und aktualisiert ans Backend zurück geschickt werden.

2021-01-03 17:23 UTC, bbortt commented
> 
> 
> Wenn ich ein Event bearbeite erhalte ich einen `Interner Serverfehler`
> ![image](https://user-images.githubusercontent.com/41778593/103484359-8d1d6080-4dee-11eb-9e1f-3d4caf95a59b.png)

brauche einen Stacktrace.. works on my machine :P

2021-01-06 17:06 UTC, zeroplexer approved these changes
LGTM

2021-01-06 17:06 UTC, merged