Bugfix/#162 enhanced invitation security
bbortt/event-planner pull request #168
Opened 2021-01-16 14:20 UTC by bbortt

PR contains:
* invitation uniqueness `jhi_user_id` per `project_id`
* invitation frontend uniqueness check by `email`
* cleanup job which removes `Invitation` elder than 14 days
* email update which states the validity of the token
* invitation API security
* minor other test improvements, spelling mistakes fixed

closes #162.

2021-01-19 12:22 UTC, zeroplexer requested changes
Small changes

2021-01-19 12:22 UTC, zeroplexer commented on src/main/java/io/github/bbortt/event/planner/repository/InvitationRepository.java
> +    List<Invitation> findAllByAcceptedIsFalseAndAndTokenIsNotNullAndCreatedDateBefore(Instant dateTime);
2x `And`

2021-01-19 12:22 UTC, zeroplexer commented on src/main/java/io/github/bbortt/event/planner/web/rest/InvitationResource.java
> +    @PreAuthorize("hasAuthority(\"" + AuthoritiesConstants.ADMIN + "\")")
Secretary sollte auch Zugriff haben

2021-01-20 07:21 UTC, bbortt commented on src/main/java/io/github/bbortt/event/planner/web/rest/InvitationResource.java
> +    @PreAuthorize("hasAuthority(\"" + AuthoritiesConstants.ADMIN + "\")")
nein, dies ist der applikatorische `ADMIN` und nur dieser darf _alle_ `Invitation` auflisten.

2021-01-20 20:36 UTC, merged