#64 remove all backend caching aspects
bbortt/event-planner pull request #66
Opened 2020-11-09 19:27 UTC by Marcarrian

This is part 1 of solving this #64 issue.
Now, after creating a project, you're able to hit F5 and the screenplay and settings buttons appear as expected.

2020-11-09 19:38 UTC, bbortt requested changes
build fails.

2020-11-10 07:52 UTC, bbortt requested changes
es hat noch Dependencies im `build.gradle`: `implementation "org.springframework.boot:spring-boot-starter-cache"`. dann auch noch einige Properties. Hibernate 2nd level Cache würde ich stehen lassen, aber JHipster / Ehcache Properties können weg. Rest sieht ok aus. thx!

2020-11-10 08:56 UTC, Marcarrian commented
@bbortt Ah du meinst alle @Cache Annotationen soll ich so belassen?

2020-11-10 11:46 UTC, bbortt commented
nein, das ist gut so. die Annotationen kümmern sich um den externen Cache (hier Ehcache). Hibernate 2nd level Cache kannst du nicht im Code annotieren, das passiert automatisch. ich rede von den Properties.

2020-11-10 14:04 UTC, Marcarrian commented
Ah, danke. Dann entferne ich noch die properties.

2020-11-11 15:53 UTC, bbortt commented
@Marcarrian die Properties fehlen noch, oder sehe ich sie nicht?

2020-11-11 16:57 UTC, zeroplexer approved these changes
LGTM

2020-11-11 16:57 UTC, bbortt approved these changes

2020-11-11 18:04 UTC, merged