#81 fix project card responsive display.
bbortt/event-planner pull request #93
Opened 2020-11-29 14:31 UTC by bbortt

# Project cards on desktops:
![image](https://user-images.githubusercontent.com/12272901/100544666-9b101c80-3257-11eb-86bd-a072be83ecdf.png)

# Project cards on mobile:
![image](https://user-images.githubusercontent.com/12272901/100544683-aa8f6580-3257-11eb-9528-463d0fb66839.png)

# Project card button alignment:
![image](https://user-images.githubusercontent.com/12272901/100544704-c85cca80-3257-11eb-85c8-2141c9778fdf.png)

# Project-administrative navigation on mobile:
![image](https://user-images.githubusercontent.com/12272901/100544696-bc710880-3257-11eb-9aad-f4b3d8a77908.png)

Part of #81.

2020-11-30 08:10 UTC, zeroplexer commented
Bitte zwischen dem Titel "Meine Projekte" und die 2 Buttons "Alle Projekte anzeigen" und "Projekt erstellen" abstand hinzufügen. Wie auch zwischen den 2 Buttons. 
Der Rahmen und die Hintergrundfarbe der Beschreibung finde ich bisschen komisch. Sieht bisschen wie ein disabled Inputfeld aus.

2020-11-30 08:10 UTC, zeroplexer requested changes
Bitte zwischen dem Titel "Meine Projekte" und die 2 Buttons "Alle Projekte anzeigen" und "Projekt erstellen" abstand hinzufügen. Wie auch zwischen den 2 Buttons.
Der Rahmen und die Hintergrundfarbe der Beschreibung finde ich bisschen komisch. Sieht bisschen wie ein disabled Inputfeld aus.

2020-11-30 19:10 UTC, bbortt commented
@zeroplexer now looks like this:

![image](https://user-images.githubusercontent.com/12272901/100653032-15b86500-3348-11eb-9387-c4e48281d3e7.png)

2020-12-02 12:42 UTC, zeroplexer approved these changes
Tiptop, dass passt so für mich

2020-12-03 07:42 UTC, merged